FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

EXPOSE 3000

# Start Next.js development server on 0.0.0.0 so Nginx can access it
CMD ["pnpm", "dev", "--hostname", "0.0.0.0"]
